### ISSUE TITLE
ValueError with providers for InferenceSession()

### ISSUE THREAD

**Issue by Gaurav0502** [arsenyinfo/EnlightenGAN-inference#4]
The pip install for the repository code works perfectly fine but when executing the inference session, it results in the following ValueError:

This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

The code executed:
```python
from enlighten_inference import EnlightenOnnxModel
import cv2

img = cv2.imread('/path/to/image.jpg')
model = EnlightenOnnxModel() # Value Error

processed = model.predict(img)
```
(The one given in the README.md file.)

**Comment by arsenyinfo** [comment]
Hey @Gaurav0502 , I just pushed a quick fix, please try it!

**Comment by Gaurav0502** [comment]
Tried the fix it worked. Thanks @arsenyinfo!
